# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - 5435:5432
    volumes:
      - database_data:/var/lib/postgresql/data