# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bookingDB
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - 5433:5432
    volumes:
      - database_data:/var/lib/postgresql/data